# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCxOIjpmHz1KRQTZZ45ZVVljKfyoE2Zc
"""

def tashxis(belgi):
  if belgi=="istima":
    return "parastamol iching"
  elif belgi=="bosh og'rig'i":
    return "trimol iching"
  elif belgi=="gripp":
    return "griphot iching"
  else:
    return "Shifokorga murojat qiling"
belgi= input("kasallik belgisini kiriting")
natija=tashxis(belgi)
print(natija)

from google.colab.patches import cv2_imshow
import cv2
def telefon(rusmi):
  if rusmi=="redmi note 12":
    rasm=cv2.imread("1.jpg")
    cv2_imshow(rasm)
    return "narxi 1.200.000"
  elif rusmi=="redmi note 13 pro ":
    rasm=cv2.imread("redmi 13.jpg")
    cv2_imshow(rasm)
    return "narxi: 4.200.000"
  elif rusmi=="iphone 16 pro max":
    rasm=cv2.imread("iphone 16.jpg")
    cv2_imshow(rasm)
    return "narxi: 25.000.000"
  elif rusmi=="Honor 200 lite ":
    rasm=cv2.imread("honor 200.jpg")
    cv2_imshow(rasm)
    return "narxi: 5.400.000"
  elif rusmi=="infinix GT 20 pro":
    rasm=cv2.imread("29 pro.jpg")
    cv2_imshow(rasm)
    return "narxi: 5.000.000"
  elif rusmi=="iphone 14 pro max":
    rasm=cv2.imread("14 max.pnj")
    cv2_imshow(rasm)
    return "narxi: 10.000.000"
  elif rusmi=="poco F6 pro ":
    rasm=cv2.imread("poco.pnj")
    cv2_imshow(rasm)
    return "narxi: 6.000.000"
  elif rusmi=="redmegic 7 pro":
    rasm=cv2.imread("redmegic.jpg")
    cv2_imshow(rasm)
    return "narxi: 9.000.000"
  else:
    return "Telefon haqida ma'lumot kerak bo'lsa bizga murojat qiling"
rusmi= input("Telefon markasini kiriting:")
natija=telefon(rusmi)
print(natija)

from google.colab.patches import cv2_imshow
import cv2
def telefon(rusmi):
  if rusmi=="redmi note 12":
     rasm=cv2.imread("1.jpg")
     cv2_imshow(rasm)
rusmi= input("Telefon markasini kiriting:")
natija=tashxis(rusmi)
print(natija)